Catching File Exceptions in openpower-vpd-parser
ibm-openbmc/openpower-vpd-parser pull request #136
Opened 2023-07-05 06:20 UTC by jinuthomas

In this commit, I have added code to handle file exceptions more effectively. By implementing proper exception handling, we can improve the robustness and reliability of the file operations within our codebase.

Here are the key changes made in this commit:

  - Introduced a try-catch block around the file operation sections.
  - Within the try block, added code to perform the necessary file operations.
  - Implemented catch blocks to handle specific file exceptions.
  - In each catch block, included appropriate error handling logic, such as logging the error message or displaying a user-friendly error message.
  - Ensured that the catch blocks gracefully handle the exceptions and prevent the program from crashing or behaving unexpectedly.

By adding this exception handling code, we can anticipate and handle potential file-related errors gracefully, providing a smoother experience for users and preventing any unexpected crashes or data loss. This would also aid in debugging issues.

2023-07-05 06:21 UTC, jinuthomas commented
jenkins run tests please

2023-07-10 03:59 UTC, jinuthomas commented on impl.hpp
> +                      << "] error : " << fail.what();
the std::err has the description so did not add error();

2023-07-10 04:00 UTC, jinuthomas commented on vpd_tool_impl.cpp
> +    vpdFileStream.exceptions(std::ifstream::badbit);
added it , not sure if it is useful , so initially was reluctant to add it .

2023-07-10 05:41 UTC, GiridhariKrishnan commented on impl.hpp
> +                      << "] error : " << fail.what();
Oh Okay, but I think it won't give errno description, if any like error().

2023-07-10 05:42 UTC, GiridhariKrishnan approved these changes

2023-07-10 07:16 UTC, PriyangaRamasamy approved these changes

2023-07-10 09:04 UTC, SunnySrivastava1984 approved these changes

2023-07-10 12:12 UTC, GiridhariKrishna approved these changes

2023-07-10 13:47 UTC, SunnySrivastava1984 requested changes
CI failing. Once it is passed I will approve.

2023-07-11 08:54 UTC, PriyangaRamasamy commented
jenkins run tests please

2023-07-11 09:34 UTC, Alpana07 approved these changes
Code looks okay to me.

2023-07-12 06:06 UTC, SunnySrivastava1984 approved these changes

2023-07-12 06:43 UTC, merged