P11 Dev: Gtest cases for IPZ parser
ibm-openbmc/openpower-vpd-parser pull request #223
Opened 2024-03-12 11:15 UTC by branupama

Adding different google unit test cases to verify whether IPZ parser is working for different VPD input.

Test:
Observed all google test cases got passed with different inputs to IPZ parser.

2024-03-12 12:15 UTC, PriyangaRamasamy requested changes
1. Can you write a test case which hits the error "Unable to determine VPD format".
2. Can you get the code coverage report for your gtest cases to get details on number of lines and functions covered and also the ones which are uncovered.

2024-03-12 15:04 UTC, SunnySrivastava1984 requested changes

2024-03-13 12:30 UTC, branupama commented on test/utest_ipz_parser.cpp
> +}
Empty vector can't be reached to Parser class, it is handled in the parser_factory.cpp itself.

2024-03-13 12:30 UTC, branupama commented on test/utest_ipz_parser.cpp
> +}
Handled in the 'MissingHeader' test case.

2024-03-13 12:30 UTC, branupama commented on test/utest_ipz_parser.cpp
> +}
As we are passing dummy vpdecc.c file for compiling through Jenkins/locally, ECC check will always be passed in this case.
Added test cases 'InvalidRecordOffset' & 'InvalidRecordEccOffset' to check invalid Record offset & Record ECC Offset in the VPD file.

2024-03-13 12:30 UTC, branupama commented on test/utest_ipz_parser.cpp
> +}
Covered in the 'GoodTestCase' test case.

2024-03-13 12:30 UTC, branupama commented on test/utest_ipz_parser.cpp
> +using namespace vpd;
Done

2024-03-13 12:30 UTC, branupama commented on test/utest_ipz_parser.cpp
> +        std::get<types::IPZVpdMap>(l_vpdParser.parse());
Updated the code.

2024-03-13 12:31 UTC, branupama commented on test/utest_ipz_parser.cpp
> +#include "exceptions.hpp"
Updated the code.

2024-03-13 12:34 UTC, branupama commented on test/utest_ipz_parser.cpp
> +TEST(IpzVpdParserTest, VpdFileNotExists)
Updated.

2024-04-08 13:06 UTC, SunnySrivastava1984 approved these changes

2024-04-10 06:39 UTC, merged