Initiate non blocking threads for collection
ibm-openbmc/openpower-vpd-parser pull request #261
Opened 2024-06-24 06:50 UTC by SunnySrivastava1984

Instantiate threads to collect FRU in a separate thread so that main thread is not blocked till the collection is in progress.

2024-06-27 07:38 UTC, branupama commented on src/manager.cpp
> +    static boost::asio::steady_timer timer(*m_ioContext);
local variables should starts with l_

2024-06-27 07:38 UTC, branupama commented on src/manager.cpp
> +                    "Waiting... FRU VPD collection in progress");
is in progress .?

2024-06-27 07:38 UTC, branupama commented on src/manager.cpp
> +            if (timerCount == MAX_RETRY)
timerCount should increment ?

2024-06-27 07:38 UTC, branupama commented on include/worker.hpp
> +    // Keeps track of active thread doing VPD collection.
Nits: threads count

2024-06-27 07:38 UTC, branupama commented on src/worker.cpp
> +            auto futureObject = std::async(&Worker::parseAndPublishVPD, this,
l_futureObject

2024-06-27 07:38 UTC, branupama commented on src/worker.cpp
> +                activeCollectionThreadCount--;
can we keep this outside ?

2024-06-27 08:53 UTC, SunnySrivastava1984 commented on src/manager.cpp
> +    static boost::asio::steady_timer timer(*m_ioContext);
done

2024-06-27 08:53 UTC, SunnySrivastava1984 commented on src/manager.cpp
> +            if (timerCount == MAX_RETRY)
Fixed.

2024-06-27 08:53 UTC, SunnySrivastava1984 commented on src/worker.cpp
> +                activeCollectionThreadCount--;
yes we can.

2024-06-27 12:05 UTC, branupama requested changes

2024-06-27 12:05 UTC, branupama commented on src/manager.cpp
> +                timer.cancel();
l_timer ?

2024-06-27 12:05 UTC, branupama commented on src/worker.cpp
> +            else if (std::get<0>(l_threadInfo))
can we use else here directly. ?

2024-07-01 01:10 UTC, branupama approved these changes

2024-07-01 03:37 UTC, merged