utils:API to get redundant EEPROM path from JSON
ibm-openbmc/openpower-vpd-parser pull request #269
Opened 2024-06-28 11:32 UTC by PriyangaRamasamy

Test cases covered:
1. Given a redundant EEPROM path, get back the same.
2. Given an inventory dbus path, get back the redundant EEPROM path taken from JSON.
3. Given a FRU EEPROM path, get back the redundant EEPROM path taken from JSON.

2024-06-28 13:09 UTC, SunnySrivastava1984 requested changes
Commit message does not state any usability of this API.Please add a proper commit message.

2024-07-01 05:06 UTC, SunnySrivastava1984 requested changes

2024-07-01 05:06 UTC, SunnySrivastava1984 commented on src/utils.cpp
> +        if (l_redundantFruPath == std::string())
If possible, always make use of library functions, its more generic.

https://stackoverflow.com/questions/483337/c-is-string-empty-always-equivalent-to-string

2024-07-02 09:03 UTC, branupama requested changes

2024-07-02 09:21 UTC, PriyangaRamasamy commented on include/utils.hpp
> + * @param[in] i_sysCfgJsonObj - system config JSON object
?

2024-07-02 09:52 UTC, branupama commented on include/utils.hpp
> + * @param[in] i_sysCfgJsonObj - system config JSON object
Nit: System config JSON object.

2024-07-03 06:07 UTC, SunnySrivastava1984 approved these changes

2024-07-03 06:07 UTC, jinuthomas approved these changes

2024-07-03 06:07 UTC, merged