IPZ:API to read IPZ keyword from hardware
ibm-openbmc/openpower-vpd-parser pull request #292
Opened 2024-07-11 08:31 UTC by PriyangaRamasamy

This commit implements API to read keyword value from hardware in IpzVpdParser class.

Test:
Test works as expected.

2024-07-12 11:57 UTC, SunnySrivastava1984 requested changes

2024-07-12 11:57 UTC, SunnySrivastava1984 commented on src/ipz_parser.cpp
> +        throw types::DeviceError::ReadFailure();
Why it is a device error if data set by the user is wrong? I would suggest a generic runtime error or invalid argument would suit more.

2024-07-15 06:35 UTC, PriyangaRamasamy commented
jenkins run tests please

2024-07-15 09:58 UTC, PriyangaRamasamy commented
rebased this PR on latest P11_Dev with the last patchset https://github.com/ibm-openbmc/openpower-vpd-parser/commit/8a8dc2945281c28412b68757e967ce876cb2c351

2024-07-16 04:38 UTC, SunnySrivastava1984 approved these changes

2024-07-16 06:55 UTC, jinuthomas reviewed
waiting for PR 291 , also restrict VHDR and VTOC for the time being , keep code commented , do not remove the code. retune as invalid arg for the time being .

2024-07-17 10:12 UTC, jinuthomas commented on include/ipz_parser.hpp
> +     * @return On success return the value read from hardware. On failure
nit: same as below

2024-07-17 14:13 UTC, PriyangaRamasamy commented on include/ipz_parser.hpp
> +     * @return On success return the value read from hardware. On failure
done

2024-07-18 03:34 UTC, jinuthomas approved these changes

2024-07-18 03:34 UTC, merged