Fix memory leak in backup and restore VPD (#297)
ibm-openbmc/openpower-vpd-parser pull request #299
Opened 2024-07-24 13:40 UTC by branupama

Dynamically allocated memory was not released while backup and restoring the VPD, which is causing the memory leak.

Changes are made to handle the memory leak in this commit.

2024-07-25 14:56 UTC, SunnySrivastava1984 requested changes
Please fix the commit message.
> Dynamically allocated memory was not released while backup and
restoring the VPD, which is causing the memory leak.

Dynamically allocated memory was not released while backup and
restoring the VPD, which was causing memory leak.

2024-07-25 17:06 UTC, branupama commented
> Please fix the commit message.
> 
> > Dynamically allocated memory was not released while backup and
> > restoring the VPD, which is causing the memory leak.
> 
> Dynamically allocated memory was not released while backup and restoring the VPD, which was causing memory leak.

Done.

2024-07-26 04:55 UTC, SunnySrivastava1984 approved these changes

2024-07-31 06:08 UTC, jinuthomas approved these changes

2024-07-31 06:08 UTC, merged