Moving updateKeyword & dependent API’s to utility
ibm-openbmc/openpower-vpd-parser pull request #367
Opened 2024-09-13 07:35 UTC by branupama

Moving the updateKeyword and its dependent API’s from manager class to vpdSpecificUtility file.
As the same updateKeyword API ‘s implementation logic is required in the backup&restore functionality as well for updating the keyword’s value.
So, in future if any other components require this API, can call API from vpdSpecificUtility.

2024-09-17 06:12 UTC, SunnySrivastava1984 approved these changes

2024-09-17 06:13 UTC, SunnySrivastava1984 reviewed
Already approved code has just been moved around.

2024-09-18 03:19 UTC, jinuthomas requested changes
I am not convinced to have utility function needing the parser. then it will not be a utility function

2024-09-25 04:25 UTC, closed without merging

2024-09-25 04:27 UTC, branupama commented
These API's are moved  to Parser class (in different PR) instead to Utility, to avoid the Utility is depending on the Parser class.