Support DDR4 DDIMM parse
ibm-openbmc/openpower-vpd-parser pull request #422
Opened 2024-10-16 07:48 UTC by branupama

This commit adds the code to support parsing of DDR4 DDIMM type VPD.

ParserFactory is updated to handle the DDR4 type to get the DDIMM VPD parsing instance for DDR4 DDIMM and DdimmVpdParser class updated to handle DDR4 DDIMM VPD parsing with new API to calculate the DDR4 DDIMM size.

2024-11-05 09:25 UTC, jinuthomas requested changes

2024-11-05 09:25 UTC, jinuthomas commented on src/ddimm_parser.cpp
> +    else if ((i_iterator[constants::SPD_BYTE_2] & constants::SPD_BYTE_MASK) ==
why do you need an  & here ?

2024-11-05 09:25 UTC, jinuthomas commented on src/ddimm_parser.cpp
> +    size_t l_tmpValue = 0, l_dimmSize = 0;
why is l_tmpValue a size_t ?

2024-11-05 09:25 UTC, jinuthomas commented on src/ddimm_parser.cpp
> +    size_t l_primaryBusWid = 1;
why size_t ?

2024-11-05 09:25 UTC, jinuthomas commented on src/ddimm_parser.cpp
> +    size_t l_sdramWidth = 1;
why size_t ?

2024-11-05 09:25 UTC, jinuthomas commented on src/ddimm_parser.cpp
> +    size_t l_logicalRanksPerDimm = (l_tmpValue + 1) * l_dieCount;
why size_t ?

2024-11-05 09:25 UTC, jinuthomas commented on src/ddimm_parser.cpp
> +        logging::logMessage(
TODO:: need an error log here

2024-11-07 15:44 UTC, branupama commented on src/ddimm_parser.cpp
> +    size_t l_tmpValue = 0, l_dimmSize = 0;
Updated

2024-11-07 15:44 UTC, branupama commented on src/ddimm_parser.cpp
> +    size_t l_primaryBusWid = 1;
updated

2024-11-07 15:44 UTC, branupama commented on src/ddimm_parser.cpp
> +    size_t l_sdramWidth = 1;
updated

2024-11-07 15:44 UTC, branupama commented on src/ddimm_parser.cpp
> +    size_t l_logicalRanksPerDimm = (l_tmpValue + 1) * l_dieCount;
updated

2024-11-07 15:44 UTC, branupama commented on src/ddimm_parser.cpp
> +        logging::logMessage(
Done

2024-11-07 16:58 UTC, branupama commented on src/ddimm_parser.cpp
> +    else if ((i_iterator[constants::SPD_BYTE_2] & constants::SPD_BYTE_MASK) ==
removed

2024-11-11 04:00 UTC, jinuthomas approved these changes

2024-11-11 04:00 UTC, merged