PEL for Worker class
ibm-openbmc/openpower-vpd-parser pull request #545
Opened 2024-12-17 03:53 UTC by RekhaAparna01

This commit adds code to log a PEL in worker class, in case of error where PEL is required.

2024-12-18 07:01 UTC, SunnySrivastava1984 requested changes

2024-12-18 17:01 UTC, RekhaAparna01 commented on vpd-manager/src/worker.cpp
> +        EventLogger::createAsyncPel(
Done

2025-01-21 04:44 UTC, SunnySrivastava1984 approved these changes
There are some unrelated changes in the PR. This should not be a common practice.

2025-01-21 04:44 UTC, SunnySrivastava1984 commented on vpd-manager/src/worker.cpp
> +                types::ErrorType::InvalidVpdMessage,
Will revisit on error type and severity on use basis later on.

2025-01-21 04:44 UTC, SunnySrivastava1984 commented on vpd-manager/src/worker.cpp
> +            types::ErrorType::InvalidVpdMessage,
Severity and type will be updated in future on use basis.

2025-01-21 04:44 UTC, merged