Implement vpd-tool object dump
ibm-openbmc/openpower-vpd-parser pull request #553
Opened 2024-12-19 04:28 UTC by souvik1914581

2025-01-07 05:24 UTC, SunnySrivastava1984 requested changes

2025-01-07 05:24 UTC, SunnySrivastava1984 commented on vpd-tool/src/vpd_tool.cpp
> +    nlohmann::json l_fruJson = nlohmann::json::object_t({});
Is it required to default initialize it?

2025-01-07 05:24 UTC, SunnySrivastava1984 commented on vpd-tool/src/vpd_tool.cpp
> +    const bool l_isFruPresent = isFruPresent(i_objectPath);
If it is a one time use variable, get rid of it. Just check the return value in place.

2025-01-07 05:24 UTC, SunnySrivastava1984 commented on vpd-tool/include/tool_utils.hpp
> +/** @brief API to get list of interfaces under a given object path
nit: Put a period at end of the sentence.

2025-01-07 05:24 UTC, SunnySrivastava1984 commented on vpd-tool/include/tool_utils.hpp
> +    try
A blank line between block of code is missing.

2025-01-07 05:24 UTC, SunnySrivastava1984 commented on vpd-tool/include/tool_utils.hpp
> + * PIM under that object path. This API calls DBus method GetObject hosted by
The description is wrong. It will not give only related to PIM. It will return map of all the services implementing that object path.

2025-01-07 05:24 UTC, SunnySrivastava1984 commented on vpd-tool/include/tool_utils.hpp
> +inline types::MapperGetObject GetInterfaces(
The API gets both service name and interface. Can we come up with a more relevant name?

2025-01-07 05:24 UTC, SunnySrivastava1984 commented on vpd-tool/src/vpd_tool.cpp
> +    if (l_serviceInfMap.contains(constants::inventoryManagerService))
What will happen if it does not contain?

2025-01-07 05:24 UTC, SunnySrivastava1984 commented on vpd-tool/src/vpd_tool.cpp
> +    for (const auto& l_interface : l_pimInfList)
Should we traverse if the service PIM is not found in map?

2025-01-07 05:24 UTC, SunnySrivastava1984 commented on vpd-tool/src/vpd_tool.cpp
> +    const auto l_viniPropertiesInJson = getVINIPropertiesJson(i_objectPath);
Why do we need a separate API for VINI? VINI record is also published as an interface, is it possible to use common API for all?

2025-01-07 05:58 UTC, souvik1914581 commented on vpd-tool/include/tool_utils.hpp
> +inline types::MapperGetObject GetInterfaces(
How about `GetServiceInterfacesForObject()`?

2025-01-07 06:04 UTC, souvik1914581 commented on vpd-tool/src/vpd_tool.cpp
> +    nlohmann::json l_fruJson = nlohmann::json::object_t({});
Yes, since this API returns an empty JSON object in case the "Present" property of the FRU is not true.

2025-01-07 06:53 UTC, souvik1914581 commented on vpd-tool/src/vpd_tool.cpp
> +    const auto l_viniPropertiesInJson = getVINIPropertiesJson(i_objectPath);
`getVINIPropertiesJson()` is a convenience method.
`getVINIPropertiesJson()` accepts a list of VINI keywords(default arg : `{"SN", "PN", "CC", "FN", "DR"}` ) and calls `getInventoryPropertyJson()` for each keyword.

2025-01-07 06:54 UTC, souvik1914581 commented on vpd-tool/src/vpd_tool.cpp
> +    if (l_serviceInfMap.contains(constants::inventoryManagerService))
Addressed. Brought the `for` loop inside the `if` check. If PIM interface is not present in `l_serviceInfMap`, the API returns an empty JSON.

2025-01-07 06:55 UTC, souvik1914581 commented on vpd-tool/include/tool_utils.hpp
> +    try
Addressed.

2025-01-07 10:33 UTC, SunnySrivastava1984 commented on vpd-tool/src/vpd_tool.cpp
> +    nlohmann::json l_fruJson = nlohmann::json::object_t({});
So if it is  not initialized we can't return?
I mean -  "nlohmann::json l_fruJson" will not suffice?

2025-01-07 10:33 UTC, SunnySrivastava1984 commented on vpd-tool/src/vpd_tool.cpp
> +    const auto l_viniPropertiesInJson = getVINIPropertiesJson(i_objectPath);
that is what I am thinking. Why "getInventoryPropertyJson" can't take VINI interface and then print all the keywords under it?
Is there a restriction on kwds?

2025-01-07 12:18 UTC, souvik1914581 commented on vpd-tool/src/vpd_tool.cpp
> +    nlohmann::json l_fruJson = nlohmann::json::object_t({});
Addressed.

2025-01-07 12:18 UTC, souvik1914581 commented on vpd-tool/include/tool_utils.hpp
> + * PIM under that object path. This API calls DBus method GetObject hosted by
Addressed this.

2025-01-08 05:50 UTC, SunnySrivastava1984 requested changes

2025-01-08 05:50 UTC, SunnySrivastava1984 commented on vpd-tool/src/vpd_tool.cpp
> +        l_fruObject.insert(l_prettyNameInJson.cbegin(),
insert needs exception safety?

2025-01-08 05:50 UTC, SunnySrivastava1984 commented on vpd-tool/include/tool_utils.hpp
> +        std::vector<std::string>{constants::inventoryItemInf}) noexcept
If you default the interface here, it will make it very specific and will ne be re-usable in future if needed for some other interface?

2025-01-08 05:55 UTC, souvik1914581 commented on vpd-tool/src/vpd_tool.cpp
> +        l_fruObject.insert(l_prettyNameInJson.cbegin(),
Yes, `insert()` can throw `json::exception`. This is captured in `getFruProperties` doxygen.

2025-01-08 05:56 UTC, souvik1914581 commented on vpd-tool/include/tool_utils.hpp
> +        std::vector<std::string>{constants::inventoryItemInf}) noexcept
Its still re-usable right? The caller can pass some other interface(s).

2025-01-08 06:13 UTC, souvik1914581 commented on vpd-tool/include/tool_utils.hpp
> +        std::vector<std::string>{constants::inventoryItemInf}) noexcept
ok, I agree the intention of the API is not to be specific to item interface.

2025-01-10 14:15 UTC, SunnySrivastava1984 commented on vpd-tool/include/vpd_tool.hpp
> +     * @brief Get any Inventory Property in JSON.
nits: inventory and property is in caps. Any specific reason?

2025-01-10 14:59 UTC, souvik1914581 commented on vpd-tool/include/vpd_tool.hpp
> +     * @brief Get any Inventory Property in JSON.
Addressed.

2025-01-12 10:15 UTC, SunnySrivastava1984 approved these changes

2025-01-12 10:15 UTC, merged