ECC correction of VPD
ibm-openbmc/openpower-vpd-parser pull request #82
Opened 2022-11-16 11:50 UTC by GiridhariKrishnan

ECC corrects VPD data in 32:1 bit ratio in the
event of corruption.

2023-02-15 05:32 UTC, SunnySrivastava1984 requested changes
This PR has merge conflicts, please fix that.

2023-02-15 12:05 UTC, GiridhariKrishnan commented
> This PR has merge conflicts, please fix that.

Yes, that is due to updation of base 1050 branch, fixing that.

2023-02-16 05:03 UTC, SunnySrivastava1984 requested changes
The commit header is misleading. It appears as if it corrects ECC of VPD.

2023-02-16 06:46 UTC, jinuthomas requested changes

2023-02-16 06:46 UTC, jinuthomas commented on vpd-manager/editor_impl.cpp
> +    std::advance(itrToRecordData, thisRecord.recOffset);
check offset if need to be one less or not

2023-02-16 06:46 UTC, jinuthomas commented on vpd-manager/editor_impl.cpp
> +    std::advance(itrToRecordECC, thisRecord.recECCoffset);
same as above

2023-02-16 06:46 UTC, jinuthomas commented on vpd-manager/editor_impl.cpp
> +               checkRecordECC();
lets check this in demo

2023-02-16 06:46 UTC, jinuthomas commented on vpd-manager/editor_impl.hpp
> +    /** @brief Method to check the record's Data before updating */
better brief if possible

2023-02-16 06:46 UTC, jinuthomas commented on vpd-manager/manager.cpp
> +                                          systemVpdFilePath, 0);
No magic numbers

2023-02-16 06:46 UTC, jinuthomas commented on vpd-parser/ipz_parser.hpp
> +    const std::string vpdPath;
vpdFilePath

2023-02-16 06:46 UTC, jinuthomas commented on vpd-parser/ipz_parser.hpp
> +    uint32_t offset;
vpdStartOffset

2023-02-16 06:46 UTC, jinuthomas commented on vpd-parser/parser_factory.cpp
> +                             const std::string& file, uint32_t offset)
use understandable variable names as mentioned before

2023-02-16 06:46 UTC, jinuthomas commented on vpd-parser/parser_factory.hpp
>       * @return - Pointer to concrete parser class object.
Params missing

2023-02-16 06:46 UTC, jinuthomas commented on vpd_tool_impl.cpp
> +        constants::systemVpdFilePath, 0);
NO magic numbers please

2023-02-16 06:46 UTC, jinuthomas commented on vpd_tool_impl.cpp
> +    uint32_t offset = 0;
vpdStartOffset

2023-02-17 19:43 UTC, SunnySrivastava1984 commented
@GiridhariKrishnan As discussed, Please push the PR on Gerrit.

2023-03-13 17:11 UTC, jinuthomas reviewed
Looks Good to me, just one question
If vpdFileStream.open fails 
what will vpdFileStream.seek give ? Do we need to check if it is open before trying a seek ?

2023-04-04 10:58 UTC, jinuthomas approved these changes

2023-04-04 10:58 UTC, merged